export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "callout"; text: string };

export interface BlogPost {
  slug: { en: string; fr: string };
  title: { en: string; fr: string };
  description: { en: string; fr: string };
  keywords: { en: string[]; fr: string[] };
  publishedAt: string;
  readingMinutes: number;
  relatedToolSlug: string;
  relatedToolLabel: { en: string; fr: string };
  content: { en: ContentBlock[]; fr: ContentBlock[] };
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: { en: "how-to-convert-pdf-to-word", fr: "comment-convertir-pdf-en-word" },
    title: {
      en: "How to Convert a PDF to Word (Free, No Software Needed)",
      fr: "Comment convertir un PDF en Word (Gratuit, sans logiciel)",
    },
    description: {
      en: "Learn how to convert any PDF to an editable Word document in seconds — no software, no account, no upload to servers. Step-by-step guide.",
      fr: "Apprenez à convertir n'importe quel PDF en document Word modifiable en quelques secondes — sans logiciel, sans compte, sans envoi à un serveur.",
    },
    keywords: {
      en: ["convert pdf to word", "pdf to docx free", "pdf to word online no signup", "how to edit a pdf in word", "pdf to word converter"],
      fr: ["convertir pdf en word", "pdf en docx gratuit", "comment modifier un pdf dans word", "convertisseur pdf word en ligne", "transformer pdf en word"],
    },
    publishedAt: "2025-05-15",
    readingMinutes: 5,
    relatedToolSlug: "pdf-to-word",
    relatedToolLabel: { en: "Try our PDF to Word converter", fr: "Essayer notre convertisseur PDF en Word" },
    content: {
      en: [
        { type: "p", text: "Converting a PDF to a Word document is one of the most common file tasks — whether you received a contract you need to edit, a report to update, or a form to fill in. The good news: you can do it in seconds, entirely in your browser, without installing any software or creating an account." },
        { type: "h2", text: "Why convert PDF to Word?" },
        { type: "p", text: "PDFs are designed for presentation, not editing. They lock the content into a fixed layout. Word documents (.docx), on the other hand, are fully editable. Converting a PDF to Word lets you change text, update numbers, add or remove sections, and reformat the document as you need." },
        { type: "ul", items: [
          "Edit contracts, reports, and forms without retyping everything",
          "Copy and paste text accurately from a PDF",
          "Update outdated documents without starting from scratch",
          "Collaborate with others who prefer Word format",
        ]},
        { type: "h2", text: "Step-by-step: how to convert PDF to Word" },
        { type: "ol", items: [
          "Open the PDF to Word tool in your browser — no signup required.",
          "Click the upload area or drag your PDF file onto it. Files up to 50 MB are supported.",
          "Click the Convert button. The conversion runs entirely in your browser — your file is never sent to a server.",
          "Once complete, click Download to save your .docx file.",
          "Open the file in Microsoft Word, Google Docs, or LibreOffice to edit it.",
        ]},
        { type: "callout", text: "Your file never leaves your device. The conversion uses your browser's computing power, so your documents remain completely private." },
        { type: "h2", text: "What to expect from the conversion" },
        { type: "p", text: "The quality of the conversion depends on how the PDF was created. PDFs made from Word or other text software (digital PDFs) convert very well — the text, paragraphs, headings, and basic formatting are preserved accurately." },
        { type: "p", text: "PDFs created from scanned paper documents are different. They are essentially images inside a PDF. To extract text from scanned PDFs, you need OCR (optical character recognition). Our tool handles digital PDFs. For scanned PDFs, try our OCR tool first." },
        { type: "h3", text: "Common issues and how to fix them" },
        { type: "ul", items: [
          "Multi-column layouts may need manual cleanup — PDF columns are complex to preserve",
          "Custom fonts may be substituted with standard fonts in Word",
          "Tables with complex borders may need reformatting",
          "Embedded images keep their position but may need repositioning",
        ]},
        { type: "h2", text: "Alternatives if the conversion is imperfect" },
        { type: "p", text: "If the converted Word file needs a lot of cleanup, consider these approaches: copy the text from the converted document, then paste it into a fresh Word file and reformat. This often takes less time than fixing a complex converted layout." },
        { type: "p", text: "For PDFs with mostly text (no complex tables or multi-column layouts), the conversion will be very clean. For highly formatted PDFs like annual reports or brochures, some manual touch-up should be expected — that is a limitation of the PDF format itself, not of any conversion tool." },
        { type: "h2", text: "Frequently asked questions" },
        { type: "h3", text: "Is it free?" },
        { type: "p", text: "Yes, completely free with no file size caps hidden behind a paywall. Files up to 50 MB are supported without any account." },
        { type: "h3", text: "Is my PDF safe?" },
        { type: "p", text: "Your PDF is processed entirely in your browser — it is never uploaded to any server. Once you close the tab, no trace of your file remains." },
        { type: "h3", text: "Can I convert multiple PDFs at once?" },
        { type: "p", text: "The tool processes one PDF at a time. For multiple files, simply repeat the process for each one." },
      ],
      fr: [
        { type: "p", text: "Convertir un PDF en document Word est l'une des tâches les plus courantes — que vous ayez reçu un contrat à modifier, un rapport à mettre à jour, ou un formulaire à remplir. La bonne nouvelle : vous pouvez le faire en quelques secondes, entièrement dans votre navigateur, sans installer de logiciel ni créer de compte." },
        { type: "h2", text: "Pourquoi convertir un PDF en Word ?" },
        { type: "p", text: "Les PDF sont conçus pour la présentation, pas pour l'édition. Ils figent le contenu dans une mise en page fixe. Les documents Word (.docx), en revanche, sont entièrement modifiables. Convertir un PDF en Word vous permet de modifier le texte, mettre à jour des chiffres, ajouter ou supprimer des sections, et reformater le document selon vos besoins." },
        { type: "ul", items: [
          "Modifier des contrats, rapports et formulaires sans tout retaper",
          "Copier et coller du texte avec précision depuis un PDF",
          "Mettre à jour des documents obsolètes sans repartir de zéro",
          "Collaborer avec des personnes qui préfèrent le format Word",
        ]},
        { type: "h2", text: "Étape par étape : comment convertir un PDF en Word" },
        { type: "ol", items: [
          "Ouvrez l'outil PDF en Word dans votre navigateur — sans inscription.",
          "Cliquez sur la zone de dépôt ou faites glisser votre fichier PDF. Les fichiers jusqu'à 50 Mo sont acceptés.",
          "Cliquez sur Convertir. La conversion s'effectue entièrement dans votre navigateur — votre fichier n'est jamais envoyé à un serveur.",
          "Une fois terminé, cliquez sur Télécharger pour enregistrer votre fichier .docx.",
          "Ouvrez le fichier dans Microsoft Word, Google Docs ou LibreOffice pour le modifier.",
        ]},
        { type: "callout", text: "Votre fichier ne quitte jamais votre appareil. La conversion utilise la puissance de calcul de votre navigateur, donc vos documents restent totalement privés." },
        { type: "h2", text: "À quoi s'attendre de la conversion" },
        { type: "p", text: "La qualité de la conversion dépend de la façon dont le PDF a été créé. Les PDF créés depuis Word ou un autre logiciel de traitement de texte (PDF numériques) se convertissent très bien — le texte, les paragraphes, les titres et la mise en forme de base sont préservés avec précision." },
        { type: "p", text: "Les PDF créés à partir de documents papier numérisés sont différents. Ce sont essentiellement des images dans un PDF. Pour extraire du texte de PDF numérisés, vous avez besoin de la ROC (reconnaissance optique de caractères). Notre outil traite les PDF numériques. Pour les PDF numérisés, essayez d'abord notre outil ROC." },
        { type: "h3", text: "Problèmes courants et solutions" },
        { type: "ul", items: [
          "Les mises en page multi-colonnes peuvent nécessiter un nettoyage manuel",
          "Les polices personnalisées peuvent être remplacées par des polices standard dans Word",
          "Les tableaux avec des bordures complexes peuvent nécessiter un reformatage",
          "Les images intégrées conservent leur position mais peuvent nécessiter un repositionnement",
        ]},
        { type: "h2", text: "Alternatives si la conversion est imparfaite" },
        { type: "p", text: "Si le fichier Word converti nécessite beaucoup de nettoyage, copiez le texte du document converti, puis collez-le dans un nouveau fichier Word et reformatez-le. Cela prend souvent moins de temps que de corriger une mise en page complexe." },
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "Est-ce gratuit ?" },
        { type: "p", text: "Oui, entièrement gratuit sans limite de taille cachée derrière un abonnement. Les fichiers jusqu'à 50 Mo sont acceptés sans compte." },
        { type: "h3", text: "Mon PDF est-il en sécurité ?" },
        { type: "p", text: "Votre PDF est traité entièrement dans votre navigateur — il n'est jamais envoyé à un serveur. Une fois l'onglet fermé, aucune trace de votre fichier ne subsiste." },
        { type: "h3", text: "Puis-je convertir plusieurs PDF à la fois ?" },
        { type: "p", text: "L'outil traite un PDF à la fois. Pour plusieurs fichiers, répétez simplement l'opération pour chacun." },
      ],
    },
  },
  {
    slug: { en: "how-to-compress-pdf", fr: "comment-compresser-un-pdf" },
    title: {
      en: "How to Compress a PDF File to a Smaller Size",
      fr: "Comment compresser un fichier PDF pour réduire sa taille",
    },
    description: {
      en: "Reduce your PDF file size without losing quality. Free, browser-based PDF compression — no upload, no software required. Works for emails, uploads, and storage.",
      fr: "Réduisez la taille de votre PDF sans perte de qualité. Compression PDF gratuite dans le navigateur — sans envoi, sans logiciel. Parfait pour les emails et l'espace de stockage.",
    },
    keywords: {
      en: ["compress pdf", "reduce pdf size", "shrink pdf file", "pdf too large to email", "compress pdf without losing quality", "free pdf compressor"],
      fr: ["compresser pdf", "réduire taille pdf", "pdf trop volumineux email", "compresser pdf sans perte qualité", "compresseur pdf gratuit"],
    },
    publishedAt: "2025-05-20",
    readingMinutes: 4,
    relatedToolSlug: "pdf-compress",
    relatedToolLabel: { en: "Try our free PDF Compressor", fr: "Essayer notre compresseur PDF gratuit" },
    content: {
      en: [
        { type: "p", text: "A PDF that is too large to email, upload, or share is one of the most frustrating everyday problems. Whether it is a scanned document, a presentation full of images, or a multi-page report, large PDFs slow everything down. Compressing a PDF reduces its file size so it is easier to share — without visually degrading the content." },
        { type: "h2", text: "Why do PDFs get so large?" },
        { type: "p", text: "PDFs become large primarily because of images. Every photo, chart, or graphic embedded in a PDF is stored at full resolution by default. A document with 10 high-resolution photos can easily reach 20–50 MB. Other factors include embedded fonts, metadata, and revision history stored inside the file." },
        { type: "ul", items: [
          "High-resolution images (the most common cause)",
          "Multiple embedded fonts",
          "Unused objects and metadata from PDF editors",
          "Revision history and annotations left in the file",
        ]},
        { type: "h2", text: "How to compress a PDF in your browser" },
        { type: "ol", items: [
          "Open the Compress PDF tool — no account needed.",
          "Upload your PDF by clicking the drop zone or dragging your file in.",
          "Click Compress. The tool resamples images and strips unused data entirely in your browser.",
          "Download the compressed PDF and compare file sizes.",
        ]},
        { type: "callout", text: "The tool reduces file size by resampling embedded images to 150 DPI — high enough for screen reading and printing, but significantly smaller than the original." },
        { type: "h2", text: "How much can a PDF be compressed?" },
        { type: "p", text: "Results vary depending on the original content. PDFs made mostly of text compress very little because text is already compact. PDFs with many high-resolution photos can shrink by 50–80%. A realistic expectation for a mixed-content PDF (text + some images) is a 30–60% reduction." },
        { type: "h3", text: "When compression has limited effect" },
        { type: "ul", items: [
          "PDFs that are mostly text — already well-optimized",
          "PDFs already compressed by the original software",
          "PDFs with low-resolution images that cannot be reduced further",
          "Encrypted or password-protected PDFs (unlock them first)",
        ]},
        { type: "h2", text: "Tips to keep PDF size small from the start" },
        { type: "p", text: "If you are creating PDFs yourself, reducing the size at source is always better than compressing after the fact. When exporting from Word, PowerPoint, or design apps, choose 'Optimize for screen' or 'Reduce file size' in the export settings. Avoid embedding high-resolution stock photos when lower-resolution versions are available." },
        { type: "h2", text: "Common uses for PDF compression" },
        { type: "ul", items: [
          "Email attachments — most email providers cap at 10–25 MB",
          "Online form uploads — many portals limit uploads to 5–10 MB",
          "Cloud storage — save space on Google Drive, Dropbox, OneDrive",
          "Sharing links — smaller PDFs load faster on mobile networks",
        ]},
        { type: "h2", text: "Frequently asked questions" },
        { type: "h3", text: "Will compression affect text quality?" },
        { type: "p", text: "No. Text in PDFs is stored as vector data, not as pixels, so it is never degraded by compression. Only embedded images are resampled." },
        { type: "h3", text: "Is there a file size limit?" },
        { type: "p", text: "Files up to 50 MB can be compressed. If your PDF is larger, try splitting it into smaller parts first using our PDF Split tool." },
      ],
      fr: [
        { type: "p", text: "Un PDF trop volumineux pour être envoyé par email, téléchargé ou partagé est l'un des problèmes quotidiens les plus frustrants. Qu'il s'agisse d'un document numérisé, d'une présentation remplie d'images ou d'un rapport de plusieurs pages, les gros PDF ralentissent tout. Compresser un PDF réduit sa taille pour faciliter le partage — sans dégrader visuellement le contenu." },
        { type: "h2", text: "Pourquoi les PDF deviennent-ils si volumineux ?" },
        { type: "p", text: "Les PDF deviennent volumineux principalement à cause des images. Chaque photo, graphique ou illustration intégré dans un PDF est stocké en pleine résolution par défaut. Un document avec 10 photos haute résolution peut facilement atteindre 20 à 50 Mo. D'autres facteurs incluent les polices intégrées, les métadonnées et l'historique des révisions stocké dans le fichier." },
        { type: "ul", items: [
          "Images haute résolution (la cause la plus fréquente)",
          "Polices multiples intégrées",
          "Objets inutilisés et métadonnées laissés par les éditeurs PDF",
          "Historique des révisions et annotations dans le fichier",
        ]},
        { type: "h2", text: "Comment compresser un PDF dans votre navigateur" },
        { type: "ol", items: [
          "Ouvrez l'outil Compresser PDF — sans compte nécessaire.",
          "Importez votre PDF en cliquant sur la zone de dépôt ou en faisant glisser votre fichier.",
          "Cliquez sur Compresser. L'outil rééchantillonne les images et supprime les données inutilisées entièrement dans votre navigateur.",
          "Téléchargez le PDF compressé et comparez les tailles de fichiers.",
        ]},
        { type: "callout", text: "L'outil réduit la taille du fichier en rééchantillonnant les images intégrées à 150 DPI — suffisamment haute pour la lecture écran et l'impression, mais bien plus petite que l'original." },
        { type: "h2", text: "De combien peut-on compresser un PDF ?" },
        { type: "p", text: "Les résultats varient selon le contenu original. Les PDF composés principalement de texte se compriment très peu car le texte est déjà compact. Les PDF avec de nombreuses photos haute résolution peuvent réduire de 50 à 80%. Une attente réaliste pour un PDF à contenu mixte (texte + quelques images) est une réduction de 30 à 60%." },
        { type: "h2", text: "Utilisations courantes de la compression PDF" },
        { type: "ul", items: [
          "Pièces jointes email — la plupart des fournisseurs limitent à 10–25 Mo",
          "Téléchargements sur formulaires en ligne — souvent limités à 5–10 Mo",
          "Stockage cloud — économisez de l'espace sur Google Drive, Dropbox, OneDrive",
          "Partage de liens — les PDF plus petits se chargent plus vite sur mobile",
        ]},
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "La compression affecte-t-elle la qualité du texte ?" },
        { type: "p", text: "Non. Le texte dans les PDF est stocké sous forme de données vectorielles, pas de pixels, donc il n'est jamais dégradé par la compression. Seules les images intégrées sont rééchantillonnées." },
        { type: "h3", text: "Y a-t-il une limite de taille de fichier ?" },
        { type: "p", text: "Les fichiers jusqu'à 50 Mo peuvent être compressés. Si votre PDF est plus grand, essayez d'abord de le diviser en parties plus petites avec notre outil Diviser PDF." },
      ],
    },
  },
  {
    slug: { en: "how-to-remove-image-background", fr: "comment-supprimer-fond-image" },
    title: {
      en: "How to Remove the Background From an Image (Free, AI-Powered)",
      fr: "Comment supprimer le fond d'une image (Gratuit, IA)",
    },
    description: {
      en: "Remove image backgrounds instantly with AI — no Photoshop, no subscription. Works for product photos, profile pictures, and logos. Free and private.",
      fr: "Supprimez les arrière-plans d'images instantanément avec l'IA — sans Photoshop, sans abonnement. Parfait pour les photos produit, les avatars et les logos.",
    },
    keywords: {
      en: ["remove image background", "background remover free", "transparent background png", "remove background from photo", "ai background removal"],
      fr: ["supprimer fond image", "supprimer arrière-plan photo", "fond transparent png", "enlever fond image gratuit", "suppression fond ia"],
    },
    publishedAt: "2025-05-25",
    readingMinutes: 4,
    relatedToolSlug: "background-remover",
    relatedToolLabel: { en: "Try our AI Background Remover", fr: "Essayer notre suppresseur de fond IA" },
    content: {
      en: [
        { type: "p", text: "Removing the background from an image used to require Photoshop skills and hours of careful selection work. Today, AI can do it in seconds. Whether you need a transparent PNG for a product photo, a clean profile picture, or a logo with no background, this guide shows you how — for free." },
        { type: "h2", text: "What is AI background removal?" },
        { type: "p", text: "AI background removal uses a machine learning model trained on millions of images to detect and separate the foreground subject (person, object, product) from the background. It produces a PNG image with a transparent background — the background becomes invisible, showing through to whatever is behind the image." },
        { type: "h2", text: "How to remove an image background in your browser" },
        { type: "ol", items: [
          "Open the Background Remover tool.",
          "Upload your image (JPG, PNG, WEBP — up to 20 MB).",
          "The AI model runs entirely in your browser using your device's computing power.",
          "Wait a few seconds for the model to process your image.",
          "Preview the result and download the transparent PNG.",
        ]},
        { type: "callout", text: "The AI runs entirely in your browser — your image is never sent to a server. This means your photos stay completely private." },
        { type: "h2", text: "What types of images work best?" },
        { type: "p", text: "Background removal AI works best when there is clear contrast between the subject and the background. The following types of images get the cleanest results:" },
        { type: "ul", items: [
          "Product photos on solid or simple backgrounds",
          "Portrait photos with a distinct background",
          "Logos and icons with clear edges",
          "Objects with well-defined outlines",
        ]},
        { type: "h3", text: "Images where results may be imperfect" },
        { type: "ul", items: [
          "Hair, fur, or fine details at the edges",
          "Transparent or semi-transparent subjects (glass, water)",
          "Subjects with the same color as the background",
          "Highly complex, cluttered backgrounds",
        ]},
        { type: "h2", text: "Common uses for transparent background images" },
        { type: "ul", items: [
          "E-commerce product images on white or colored backgrounds",
          "Profile pictures and avatars",
          "Company logos for websites and presentations",
          "Design mockups and composites",
          "Social media graphics",
        ]},
        { type: "h2", text: "Why use a browser-based tool instead of Photoshop?" },
        { type: "p", text: "Photoshop and similar desktop tools offer more fine-grained control, but they require purchase, installation, and significant expertise. For most everyday use cases — e-commerce photos, profile pictures, quick logo cleanup — a browser-based AI tool delivers results that are 90% as good in 1% of the time, with zero cost and zero installation." },
        { type: "h2", text: "Frequently asked questions" },
        { type: "h3", text: "What format does the output use?" },
        { type: "p", text: "The output is always a PNG file. PNG is the only common image format that supports full transparency." },
        { type: "h3", text: "Why is the first image slow to process?" },
        { type: "p", text: "The AI model is approximately 50 MB and loads in your browser on first use. After the first image, processing is much faster because the model stays loaded in memory during your session." },
      ],
      fr: [
        { type: "p", text: "Supprimer l'arrière-plan d'une image nécessitait autrefois des compétences Photoshop et des heures de travail minutieux. Aujourd'hui, l'IA peut le faire en quelques secondes. Que vous ayez besoin d'un PNG transparent pour une photo produit, d'une photo de profil épurée ou d'un logo sans fond, ce guide vous explique comment — gratuitement." },
        { type: "h2", text: "Qu'est-ce que la suppression de fond par IA ?" },
        { type: "p", text: "La suppression de fond par IA utilise un modèle d'apprentissage automatique entraîné sur des millions d'images pour détecter et séparer le sujet au premier plan (personne, objet, produit) de l'arrière-plan. Elle produit un fichier PNG avec un fond transparent." },
        { type: "h2", text: "Comment supprimer le fond d'une image dans votre navigateur" },
        { type: "ol", items: [
          "Ouvrez l'outil Suppresseur de fond.",
          "Importez votre image (JPG, PNG, WEBP — jusqu'à 20 Mo).",
          "Le modèle IA s'exécute entièrement dans votre navigateur.",
          "Attendez quelques secondes que le modèle traite votre image.",
          "Prévisualisez le résultat et téléchargez le PNG transparent.",
        ]},
        { type: "callout", text: "L'IA s'exécute entièrement dans votre navigateur — votre image n'est jamais envoyée à un serveur. Vos photos restent complètement privées." },
        { type: "h2", text: "Quels types d'images fonctionnent le mieux ?" },
        { type: "ul", items: [
          "Photos de produits sur fonds unis ou simples",
          "Photos portrait avec un arrière-plan distinct",
          "Logos et icônes aux contours nets",
          "Objets aux contours bien définis",
        ]},
        { type: "h2", text: "Utilisations courantes des images à fond transparent" },
        { type: "ul", items: [
          "Images de produits e-commerce sur fond blanc ou coloré",
          "Photos de profil et avatars",
          "Logos d'entreprise pour sites web et présentations",
          "Maquettes design et compositions",
          "Visuels pour réseaux sociaux",
        ]},
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "Quel format utilise le résultat ?" },
        { type: "p", text: "Le résultat est toujours un fichier PNG. Le PNG est le seul format d'image courant qui prend en charge la transparence totale." },
        { type: "h3", text: "Pourquoi la première image est-elle lente à traiter ?" },
        { type: "p", text: "Le modèle IA fait environ 50 Mo et se charge dans votre navigateur à la première utilisation. Après la première image, le traitement est beaucoup plus rapide car le modèle reste chargé en mémoire pendant votre session." },
      ],
    },
  },
  {
    slug: { en: "how-to-convert-heic-to-jpg", fr: "comment-convertir-heic-en-jpg" },
    title: {
      en: "How to Convert HEIC to JPG (Free, Works on Windows and Mac)",
      fr: "Comment convertir HEIC en JPG (Gratuit, Windows et Mac)",
    },
    description: {
      en: "Open and convert HEIC photos from your iPhone to JPG format — for free, without installing any software. Works on Windows, Mac, and Linux.",
      fr: "Ouvrez et convertissez vos photos HEIC d'iPhone au format JPG — gratuitement, sans installer de logiciel. Fonctionne sur Windows, Mac et Linux.",
    },
    keywords: {
      en: ["convert heic to jpg", "heic to jpeg free", "open heic on windows", "heic file converter", "iphone heic to jpg"],
      fr: ["convertir heic en jpg", "heic en jpeg gratuit", "ouvrir heic windows", "convertisseur heic", "iphone heic en jpg"],
    },
    publishedAt: "2025-06-01",
    readingMinutes: 5,
    relatedToolSlug: "heic-to-jpg",
    relatedToolLabel: { en: "Try our HEIC to JPG converter", fr: "Essayer notre convertisseur HEIC en JPG" },
    content: {
      en: [
        { type: "p", text: "If you have tried to open a photo taken on an iPhone on a Windows PC or share it online, you have probably encountered the HEIC format. HEIC files are smaller and higher quality than JPGs, but they are not universally supported. Converting them to JPG makes them compatible with virtually any device, app, or website." },
        { type: "h2", text: "What is HEIC?" },
        { type: "p", text: "HEIC stands for High Efficiency Image Container. Apple introduced it on iPhones in 2017 with iOS 11. HEIC images use the HEVC compression codec, which produces files about half the size of a JPG at the same visual quality. That is why iPhones default to HEIC — it saves storage space." },
        { type: "h3", text: "Why HEIC causes problems" },
        { type: "ul", items: [
          "Windows cannot open HEIC files by default (requires a paid codec or special software)",
          "Many websites refuse HEIC uploads and require JPG or PNG",
          "Older apps and programs do not recognize the format",
          "HEIC files cannot be used directly as web images",
        ]},
        { type: "h2", text: "How to convert HEIC to JPG in your browser" },
        { type: "ol", items: [
          "Open the HEIC to JPG tool.",
          "Drag your HEIC file onto the upload area, or click to select it.",
          "The conversion runs entirely in your browser — no software needed.",
          "Download the resulting JPG file.",
        ]},
        { type: "callout", text: "Your photos are converted in your browser and are never uploaded to any server. This is especially important for personal photos." },
        { type: "h2", text: "Alternative: change iPhone settings to always use JPG" },
        { type: "p", text: "If you frequently encounter HEIC compatibility issues, you can set your iPhone to take photos in JPG instead of HEIC. Go to Settings → Camera → Formats and select 'Most Compatible'. Your iPhone will then save photos as JPG by default. Note that JPG files will be larger than HEIC." },
        { type: "h2", text: "HEIC vs JPG: which is better?" },
        { type: "ul", items: [
          "HEIC: smaller files, better quality-to-size ratio, ideal for iPhone storage",
          "JPG: universal compatibility, supported by all devices and websites",
          "For sharing and web use: JPG is almost always the right choice",
          "For archiving personal photos: HEIC saves space without quality loss",
        ]},
        { type: "h2", text: "Batch conversion: convert multiple HEIC files at once" },
        { type: "p", text: "If you have a large number of HEIC photos to convert — for example, from a trip or event — our tool supports multiple files at once. You can select or drag multiple HEIC files and convert them all in a single session." },
        { type: "h2", text: "Frequently asked questions" },
        { type: "h3", text: "Does converting HEIC to JPG reduce quality?" },
        { type: "p", text: "Technically, yes — JPG is a lossy format and HEIC stores more data. However, the difference is not visible to the naked eye for most photos. If you need pixel-perfect lossless conversion, use PNG instead of JPG." },
        { type: "h3", text: "Can I open HEIC files on Windows without converting?" },
        { type: "p", text: "Yes, but it requires installing the HEIF Image Extensions from the Microsoft Store, which costs a small fee in most regions. Converting to JPG is simpler and free." },
      ],
      fr: [
        { type: "p", text: "Si vous avez essayé d'ouvrir une photo prise avec un iPhone sur un PC Windows ou de la partager en ligne, vous avez probablement rencontré le format HEIC. Les fichiers HEIC sont plus petits et de meilleure qualité que les JPG, mais ils ne sont pas universellement pris en charge. Les convertir en JPG les rend compatibles avec pratiquement n'importe quel appareil, application ou site web." },
        { type: "h2", text: "Qu'est-ce que le HEIC ?" },
        { type: "p", text: "HEIC signifie High Efficiency Image Container. Apple l'a introduit sur les iPhone en 2017 avec iOS 11. Les images HEIC utilisent le codec de compression HEVC, qui produit des fichiers environ deux fois moins volumineux qu'un JPG à qualité visuelle égale. C'est pourquoi les iPhone utilisent HEIC par défaut — cela économise de l'espace de stockage." },
        { type: "h3", text: "Pourquoi le HEIC pose problème" },
        { type: "ul", items: [
          "Windows ne peut pas ouvrir les fichiers HEIC par défaut (nécessite un codec payant)",
          "De nombreux sites refusent les téléchargements HEIC et exigent JPG ou PNG",
          "Les anciennes applications ne reconnaissent pas ce format",
          "Les fichiers HEIC ne peuvent pas être utilisés directement comme images web",
        ]},
        { type: "h2", text: "Comment convertir HEIC en JPG dans votre navigateur" },
        { type: "ol", items: [
          "Ouvrez l'outil HEIC en JPG.",
          "Faites glisser votre fichier HEIC sur la zone de dépôt, ou cliquez pour le sélectionner.",
          "La conversion s'effectue entièrement dans votre navigateur — sans logiciel.",
          "Téléchargez le fichier JPG résultant.",
        ]},
        { type: "callout", text: "Vos photos sont converties dans votre navigateur et ne sont jamais téléchargées vers un serveur. C'est particulièrement important pour les photos personnelles." },
        { type: "h2", text: "Alternative : changer les réglages iPhone pour toujours utiliser JPG" },
        { type: "p", text: "Si vous rencontrez fréquemment des problèmes de compatibilité HEIC, vous pouvez régler votre iPhone pour prendre des photos en JPG. Allez dans Réglages → Appareil photo → Formats et sélectionnez 'Plus compatible'. Les fichiers JPG seront plus volumineux que les HEIC." },
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "La conversion HEIC en JPG réduit-elle la qualité ?" },
        { type: "p", text: "Techniquement oui — le JPG est un format avec perte et le HEIC stocke plus de données. Cependant, la différence n'est pas visible à l'œil nu pour la plupart des photos. Si vous avez besoin d'une conversion sans perte, utilisez PNG plutôt que JPG." },
        { type: "h3", text: "Puis-je ouvrir des fichiers HEIC sur Windows sans les convertir ?" },
        { type: "p", text: "Oui, mais cela nécessite d'installer les Extensions d'image HEIF depuis le Microsoft Store, qui coûte une petite somme dans la plupart des régions. Convertir en JPG est plus simple et gratuit." },
      ],
    },
  },
  {
    slug: { en: "how-to-generate-strong-password", fr: "comment-creer-mot-de-passe-fort" },
    title: {
      en: "How to Generate a Strong Password (And Why It Matters)",
      fr: "Comment créer un mot de passe fort (et pourquoi c'est essentiel)",
    },
    description: {
      en: "Learn what makes a password strong, how to generate one instantly, and how to manage it safely. Free password generator — runs entirely in your browser.",
      fr: "Apprenez ce qui rend un mot de passe fort, comment en générer un instantanément et comment le gérer en toute sécurité. Générateur de mot de passe gratuit.",
    },
    keywords: {
      en: ["strong password generator", "how to create strong password", "random password free", "secure password tips", "password length security"],
      fr: ["générateur mot de passe fort", "créer mot de passe sécurisé", "mot de passe aléatoire gratuit", "conseils sécurité mot de passe", "longueur mot de passe"],
    },
    publishedAt: "2025-06-01",
    readingMinutes: 5,
    relatedToolSlug: "password-generator",
    relatedToolLabel: { en: "Generate a strong password now", fr: "Générer un mot de passe fort maintenant" },
    content: {
      en: [
        { type: "p", text: "Most people know they should use strong passwords, but few understand what actually makes a password strong — or weak. This guide explains the science behind password security and shows you how to generate truly random, strong passwords in seconds." },
        { type: "h2", text: "What makes a password strong?" },
        { type: "p", text: "Password strength is measured by how long it would take an attacker to guess it. Attackers use automated tools that can test billions of combinations per second. The two most important factors are length and randomness." },
        { type: "ul", items: [
          "Length: every extra character multiplies the number of possible combinations exponentially",
          "Randomness: predictable patterns (dates, words, keyboard walks like 'qwerty') are tested first",
          "Character variety: mixing letters, numbers, and symbols increases the search space",
          "Uniqueness: reusing passwords means one breach exposes all your accounts",
        ]},
        { type: "h3", text: "How quickly can passwords be cracked?" },
        { type: "ul", items: [
          "6 characters (letters only): cracked in under 1 second",
          "8 characters (letters + numbers): cracked in a few hours",
          "12 characters (mixed): would take thousands of years",
          "16+ characters (mixed): effectively uncrackable with current technology",
        ]},
        { type: "h2", text: "How to generate a strong password" },
        { type: "ol", items: [
          "Open the Password Generator tool.",
          "Set the length to at least 16 characters — longer is always better.",
          "Enable uppercase letters, lowercase letters, numbers, and symbols.",
          "Click Generate. The tool uses cryptographically secure randomness — the same standard used by banks and security software.",
          "Copy the password and store it in a password manager.",
        ]},
        { type: "callout", text: "The password is generated entirely in your browser. Nothing is sent to any server — we never see your password." },
        { type: "h2", text: "How to manage strong passwords" },
        { type: "p", text: "The biggest challenge with strong passwords is remembering them. A 16-character random string like 'Kx9#mR2!vP7@nL4w' is impossible to memorize. The solution is a password manager — software that stores all your passwords in an encrypted vault." },
        { type: "ul", items: [
          "Bitwarden — free, open-source, highly trusted",
          "1Password — popular with individuals and teams",
          "KeePass — local-only, no cloud sync",
          "Built-in managers in Chrome, Firefox, Safari — convenient but less secure than dedicated tools",
        ]},
        { type: "h2", text: "Frequently asked questions" },
        { type: "h3", text: "How long should a password be?" },
        { type: "p", text: "16 characters is a good minimum for important accounts. For critical accounts (email, banking, password manager itself), use 20 characters or more." },
        { type: "h3", text: "Should I use passphrases instead?" },
        { type: "p", text: "Passphrases — four or more random words — are a valid alternative. 'correct horse battery staple' is long and memorable. However, truly random character strings are slightly stronger for the same length." },
        { type: "h3", text: "How often should I change my password?" },
        { type: "p", text: "Modern security guidance (NIST 2024) no longer recommends changing passwords on a schedule. Change your password only when: you know or suspect it was compromised, after a data breach of a service you use, or if you shared it with someone." },
      ],
      fr: [
        { type: "p", text: "La plupart des gens savent qu'ils devraient utiliser des mots de passe forts, mais peu comprennent ce qui rend réellement un mot de passe fort — ou faible. Ce guide explique la science derrière la sécurité des mots de passe et vous montre comment générer des mots de passe vraiment aléatoires et forts en quelques secondes." },
        { type: "h2", text: "Qu'est-ce qui rend un mot de passe fort ?" },
        { type: "p", text: "La force d'un mot de passe se mesure au temps qu'un attaquant mettrait à le deviner. Les attaquants utilisent des outils automatisés capables de tester des milliards de combinaisons par seconde. Les deux facteurs les plus importants sont la longueur et l'aléatoire." },
        { type: "ul", items: [
          "Longueur : chaque caractère supplémentaire multiplie le nombre de combinaisons possibles de façon exponentielle",
          "Aléatoire : les modèles prévisibles (dates, mots, séquences clavier comme 'azerty') sont testés en premier",
          "Variété de caractères : mélanger lettres, chiffres et symboles augmente l'espace de recherche",
          "Unicité : réutiliser des mots de passe signifie qu'une seule fuite expose tous vos comptes",
        ]},
        { type: "h2", text: "Comment générer un mot de passe fort" },
        { type: "ol", items: [
          "Ouvrez l'outil Générateur de mot de passe.",
          "Réglez la longueur sur au moins 16 caractères — plus c'est long, mieux c'est.",
          "Activez les majuscules, minuscules, chiffres et symboles.",
          "Cliquez sur Générer. L'outil utilise une randomisation cryptographiquement sécurisée.",
          "Copiez le mot de passe et stockez-le dans un gestionnaire de mots de passe.",
        ]},
        { type: "callout", text: "Le mot de passe est généré entièrement dans votre navigateur. Rien n'est envoyé à un serveur — nous ne voyons jamais votre mot de passe." },
        { type: "h2", text: "Comment gérer des mots de passe forts" },
        { type: "p", text: "Le plus grand défi avec les mots de passe forts est de s'en souvenir. Une chaîne aléatoire de 16 caractères comme 'Kx9#mR2!vP7@nL4w' est impossible à mémoriser. La solution est un gestionnaire de mots de passe — un logiciel qui stocke tous vos mots de passe dans un coffre-fort chiffré." },
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "Quelle longueur doit avoir un mot de passe ?" },
        { type: "p", text: "16 caractères est un bon minimum pour les comptes importants. Pour les comptes critiques (email, banque, gestionnaire de mots de passe), utilisez 20 caractères ou plus." },
        { type: "h3", text: "Dois-je changer mon mot de passe régulièrement ?" },
        { type: "p", text: "Les recommandations modernes (NIST 2024) ne préconisent plus de changer les mots de passe selon un calendrier fixe. Changez votre mot de passe uniquement si vous savez ou suspectez qu'il a été compromis, ou après une fuite de données d'un service que vous utilisez." },
      ],
    },
  },
  {
    slug: { en: "webp-vs-jpeg-vs-png", fr: "webp-vs-jpeg-vs-png" },
    title: {
      en: "WebP vs JPEG vs PNG: Which Image Format Should You Use?",
      fr: "WebP vs JPEG vs PNG : quel format d'image choisir ?",
    },
    description: {
      en: "A practical guide to the three most common web image formats. Learn when to use WebP, JPEG, or PNG — and how to convert between them for free.",
      fr: "Guide pratique sur les trois formats d'image web les plus courants. Apprenez quand utiliser WebP, JPEG ou PNG — et comment les convertir gratuitement.",
    },
    keywords: {
      en: ["webp vs jpeg vs png", "best image format web", "when to use webp", "jpeg vs png difference", "convert to webp free"],
      fr: ["webp vs jpeg vs png", "meilleur format image web", "quand utiliser webp", "différence jpeg png", "convertir en webp gratuit"],
    },
    publishedAt: "2025-06-01",
    readingMinutes: 6,
    relatedToolSlug: "image-converter",
    relatedToolLabel: { en: "Convert images between formats", fr: "Convertir des images entre formats" },
    content: {
      en: [
        { type: "p", text: "Choosing the right image format is one of the most impactful decisions for web performance. The wrong choice can mean images that are 3–5× larger than necessary, slowing down your site and hurting your search rankings. This guide compares the three dominant formats — JPEG, PNG, and WebP — and tells you exactly when to use each one." },
        { type: "h2", text: "JPEG: the universal format for photos" },
        { type: "p", text: "JPEG (also written as JPG) has been the standard format for photographs since the 1990s. It uses lossy compression — meaning some image data is discarded to reduce file size. For photographs and complex images with millions of colors, JPEG produces small file sizes with excellent visual quality." },
        { type: "ul", items: [
          "Best for: photographs, product images, social media photos, any image with gradients and complex color",
          "Not good for: images with text, sharp edges, or transparency",
          "Typical file size: 50–500 KB for a full-size photo at quality 80",
          "Transparency: not supported",
        ]},
        { type: "h2", text: "PNG: the format for graphics and transparency" },
        { type: "p", text: "PNG uses lossless compression — no image data is discarded. This makes PNG significantly larger than JPEG for photographs, but it is essential for images where quality must be pixel-perfect or transparency is required." },
        { type: "ul", items: [
          "Best for: logos, icons, screenshots, graphics with text, images needing transparency",
          "Not good for: photographs (file size will be very large)",
          "Typical file size: 200 KB – 5 MB for a detailed graphic",
          "Transparency: full support (alpha channel)",
        ]},
        { type: "h2", text: "WebP: the modern format for the web" },
        { type: "p", text: "WebP was developed by Google in 2010 and is now supported by all modern browsers (Chrome, Firefox, Safari, Edge). It offers both lossy and lossless compression, and supports transparency. WebP files are typically 25–35% smaller than equivalent JPEG or PNG files." },
        { type: "ul", items: [
          "Best for: all web images — photos and graphics",
          "Lossy mode: 25–35% smaller than JPEG at equivalent quality",
          "Lossless mode: 20–30% smaller than PNG",
          "Transparency: supported",
          "Limitation: older software (Photoshop before 2020, some email clients) may not support it",
        ]},
        { type: "callout", text: "For new web projects started today, WebP should be your default format. Use JPEG as a fallback for email and older software compatibility." },
        { type: "h2", text: "Quick decision guide" },
        { type: "ul", items: [
          "Website photo → WebP (fallback JPEG)",
          "Logo or icon → WebP lossless (fallback PNG)",
          "Image with transparent background → WebP or PNG",
          "Email attachment → JPEG (best compatibility)",
          "Screenshot → PNG",
          "Printing → TIFF or PNG at 300 DPI",
        ]},
        { type: "h2", text: "How to convert between formats" },
        { type: "p", text: "Our image converter handles all conversions between JPEG, PNG, WebP, AVIF, BMP, TIFF, GIF, ICO, and SVG — in bulk, entirely in your browser, with no file size limit beyond device memory." },
        { type: "h2", text: "What about AVIF?" },
        { type: "p", text: "AVIF is the newest image format, offering 20–30% better compression than WebP. Browser support has reached 93% globally (2025), but it is slower to encode. For cutting-edge web performance, AVIF is worth considering — but WebP remains the safe, well-supported choice for most projects." },
      ],
      fr: [
        { type: "p", text: "Choisir le bon format d'image est l'une des décisions les plus impactantes pour la performance web. Un mauvais choix peut signifier des images 3 à 5 fois plus lourdes que nécessaire, ralentissant votre site et pénalisant votre référencement. Ce guide compare les trois formats dominants — JPEG, PNG et WebP — et vous dit exactement quand utiliser chacun." },
        { type: "h2", text: "JPEG : le format universel pour les photos" },
        { type: "p", text: "JPEG (aussi écrit JPG) est le format standard pour les photographies depuis les années 1990. Il utilise une compression avec perte — certaines données d'image sont supprimées pour réduire la taille du fichier. Pour les photographies et les images complexes avec des millions de couleurs, JPEG produit de petits fichiers avec une excellente qualité visuelle." },
        { type: "ul", items: [
          "Idéal pour : photographies, images de produits, photos sur réseaux sociaux, toute image avec des dégradés",
          "Déconseillé pour : images avec du texte, des bords nets ou de la transparence",
          "Taille typique : 50–500 Ko pour une photo pleine résolution à qualité 80",
          "Transparence : non prise en charge",
        ]},
        { type: "h2", text: "PNG : le format pour les graphiques et la transparence" },
        { type: "p", text: "Le PNG utilise une compression sans perte — aucune donnée d'image n'est supprimée. Cela rend le PNG sensiblement plus lourd que le JPEG pour les photographies, mais il est essentiel pour les images nécessitant une qualité pixel parfaite ou la transparence." },
        { type: "ul", items: [
          "Idéal pour : logos, icônes, captures d'écran, graphiques avec du texte, images nécessitant la transparence",
          "Déconseillé pour : photographies (taille de fichier très grande)",
          "Transparence : prise en charge complète (canal alpha)",
        ]},
        { type: "h2", text: "WebP : le format moderne pour le web" },
        { type: "p", text: "WebP a été développé par Google en 2010 et est désormais pris en charge par tous les navigateurs modernes. Il offre une compression avec et sans perte, et prend en charge la transparence. Les fichiers WebP sont généralement 25 à 35% plus petits que les fichiers JPEG ou PNG équivalents." },
        { type: "ul", items: [
          "Idéal pour : toutes les images web — photos et graphiques",
          "Mode avec perte : 25 à 35% plus petit que JPEG à qualité équivalente",
          "Mode sans perte : 20 à 30% plus petit que PNG",
          "Transparence : prise en charge",
          "Limitation : anciens logiciels (Photoshop avant 2020, certains clients email) peuvent ne pas le prendre en charge",
        ]},
        { type: "callout", text: "Pour les nouveaux projets web démarrés aujourd'hui, WebP devrait être votre format par défaut. Utilisez JPEG comme solution de secours pour la compatibilité email et les logiciels anciens." },
        { type: "h2", text: "Guide de décision rapide" },
        { type: "ul", items: [
          "Photo pour site web → WebP (secours JPEG)",
          "Logo ou icône → WebP sans perte (secours PNG)",
          "Image avec fond transparent → WebP ou PNG",
          "Pièce jointe email → JPEG (meilleure compatibilité)",
          "Capture d'écran → PNG",
          "Impression → TIFF ou PNG à 300 DPI",
        ]},
        { type: "h2", text: "Questions fréquentes" },
        { type: "h3", text: "Et le format AVIF ?" },
        { type: "p", text: "L'AVIF est le format d'image le plus récent, offrant une compression 20 à 30% meilleure que WebP. La compatibilité des navigateurs a atteint 93% globalement (2025), mais il est plus lent à encoder. Pour une performance web de pointe, l'AVIF vaut la peine d'être envisagé — mais WebP reste le choix sûr et bien pris en charge pour la plupart des projets." },
      ],
    },
  },
];

export function getBlogPostBySlug(slug: string, locale: "en" | "fr"): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug[locale] === slug);
}

export function getBlogPostByEitherSlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug.en === slug || p.slug.fr === slug);
}
