import {
  siWhatsapp,
  siTelegram,
  siInstagram,
  siX,
  siFacebook,
  siMessenger,
  siTiktok,
  siYoutube,
  siDiscord,
  siSnapchat,
  siReddit,
  siPinterest,
  siThreads,
  siTwitch,
  siWechat,
  siSpotify,
  siSoundcloud,
  siGithub,
  siSignal,
  siBluesky,
} from 'simple-icons';
import { Linkedin } from 'lucide-react';
import type { LibraryIcon } from './types';
import { createLucideLibraryIcon, createSimpleIconLibraryIcon } from './adapter';

export const SOCIAL_ICONS: LibraryIcon[] = [
  createSimpleIconLibraryIcon('whatsapp', 'WhatsApp', 'social', siWhatsapp),
  createSimpleIconLibraryIcon('telegram', 'Telegram', 'social', siTelegram),
  createSimpleIconLibraryIcon('instagram', 'Instagram', 'social', siInstagram),
  createSimpleIconLibraryIcon('x-twitter', 'X / Twitter', 'social', siX),
  createSimpleIconLibraryIcon('facebook', 'Facebook', 'social', siFacebook),
  createSimpleIconLibraryIcon('messenger', 'Messenger', 'social', siMessenger),
  createSimpleIconLibraryIcon('tiktok', 'TikTok', 'social', siTiktok),
  createSimpleIconLibraryIcon('youtube', 'YouTube', 'social', siYoutube),
  createLucideLibraryIcon('linkedin', 'LinkedIn', 'social', Linkedin),
  createSimpleIconLibraryIcon('discord', 'Discord', 'social', siDiscord),
  createSimpleIconLibraryIcon('snapchat', 'Snapchat', 'social', siSnapchat),
  createSimpleIconLibraryIcon('reddit', 'Reddit', 'social', siReddit),
  createSimpleIconLibraryIcon('pinterest', 'Pinterest', 'social', siPinterest),
  createSimpleIconLibraryIcon('threads', 'Threads', 'social', siThreads),
  createSimpleIconLibraryIcon('twitch', 'Twitch', 'social', siTwitch),
  createSimpleIconLibraryIcon('wechat', 'WeChat', 'social', siWechat),
  createSimpleIconLibraryIcon('spotify', 'Spotify', 'social', siSpotify),
  createSimpleIconLibraryIcon('soundcloud', 'SoundCloud', 'social', siSoundcloud),
  createSimpleIconLibraryIcon('github', 'GitHub', 'social', siGithub),
  createSimpleIconLibraryIcon('signal', 'Signal', 'social', siSignal),
  createSimpleIconLibraryIcon('bluesky', 'Bluesky', 'social', siBluesky),
];

