/**
 * Currency metadata: ISO country mapping, regional flags, and bilingual search keywords.
 */

export interface CurrencyMeta {
  code: string;
  countryCode?: string; // 2-letter ISO 3166-1 alpha-2 for flagcdn
  isRegional?: boolean;
  regionType?: 'XOF' | 'XAF' | 'EUR' | 'XCD' | 'XPF';
  countriesFr: string[];
  nameFr: string;
}

export const CURRENCY_META_MAP: Record<string, CurrencyMeta> = {
  AED: { code: 'AED', countryCode: 'ae', nameFr: 'Dirham des Émirats arabes unis', countriesFr: ['Émirats Arabes Unis', 'Dubaï', 'Abu Dhabi'] },
  AFN: { code: 'AFN', countryCode: 'af', nameFr: 'Afghani afghan', countriesFr: ['Afghanistan'] },
  ALL: { code: 'ALL', countryCode: 'al', nameFr: 'Lek albanais', countriesFr: ['Albanie'] },
  AMD: { code: 'AMD', countryCode: 'am', nameFr: 'Dram arménien', countriesFr: ['Arménie'] },
  ANG: { code: 'ANG', countryCode: 'cw', nameFr: 'Florin des Antilles néerlandaises', countriesFr: ['Curaçao', 'Sint Maarten'] },
  AOA: { code: 'AOA', countryCode: 'ao', nameFr: 'Kwanza angolais', countriesFr: ['Angola'] },
  ARS: { code: 'ARS', countryCode: 'ar', nameFr: 'Peso argentin', countriesFr: ['Argentine'] },
  AUD: { code: 'AUD', countryCode: 'au', nameFr: 'Dollar australien', countriesFr: ['Australie'] },
  AWG: { code: 'AWG', countryCode: 'aw', nameFr: 'Florin arubais', countriesFr: ['Aruba'] },
  AZN: { code: 'AZN', countryCode: 'az', nameFr: 'Manat azerbaïdjanais', countriesFr: ['Azerbaïdjan'] },
  BAM: { code: 'BAM', countryCode: 'ba', nameFr: 'Mark convertible bosniaque', countriesFr: ['Bosnie-Herzégovine'] },
  BBD: { code: 'BBD', countryCode: 'bb', nameFr: 'Dollar barbadien', countriesFr: ['Barbade'] },
  BDT: { code: 'BDT', countryCode: 'bd', nameFr: 'Taka bangladais', countriesFr: ['Bangladesh'] },
  BGN: { code: 'BGN', countryCode: 'bg', nameFr: 'Lev bulgare', countriesFr: ['Bulgarie'] },
  BHD: { code: 'BHD', countryCode: 'bh', nameFr: 'Dinar bahreïni', countriesFr: ['Bahreïn'] },
  BIF: { code: 'BIF', countryCode: 'bi', nameFr: 'Franc burundais', countriesFr: ['Burundi'] },
  BMD: { code: 'BMD', countryCode: 'bm', nameFr: 'Dollar bermudien', countriesFr: ['Bermudes'] },
  BND: { code: 'BND', countryCode: 'bn', nameFr: 'Dollar de Brunei', countriesFr: ['Brunei'] },
  BOB: { code: 'BOB', countryCode: 'bo', nameFr: 'Boliviano bolivien', countriesFr: ['Bolivie'] },
  BRL: { code: 'BRL', countryCode: 'br', nameFr: 'Réal brésilien', countriesFr: ['Brésil'] },
  BSD: { code: 'BSD', countryCode: 'bs', nameFr: 'Dollar bahaméen', countriesFr: ['Bahamas'] },
  BTN: { code: 'BTN', countryCode: 'bt', nameFr: 'Ngultrum bouthanais', countriesFr: ['Bhoutan'] },
  BWP: { code: 'BWP', countryCode: 'bw', nameFr: 'Pula botswanais', countriesFr: ['Botswana'] },
  BYN: { code: 'BYN', countryCode: 'by', nameFr: 'Rouble biélorusse', countriesFr: ['Biélorussie'] },
  BZD: { code: 'BZD', countryCode: 'bz', nameFr: 'Dollar bélizien', countriesFr: ['Belize'] },
  CAD: { code: 'CAD', countryCode: 'ca', nameFr: 'Dollar canadien', countriesFr: ['Canada', 'Québec'] },
  CDF: { code: 'CDF', countryCode: 'cd', nameFr: 'Franc congolais (RDC)', countriesFr: ['Congo RDC', 'Kinshasa'] },
  CHF: { code: 'CHF', countryCode: 'ch', nameFr: 'Franc suisse', countriesFr: ['Suisse', 'Genève', 'Zurich'] },
  CLP: { code: 'CLP', countryCode: 'cl', nameFr: 'Peso chilien', countriesFr: ['Chili'] },
  CNY: { code: 'CNY', countryCode: 'cn', nameFr: 'Yuan renminbi chinois', countriesFr: ['Chine', 'Pékin', 'Shanghai'] },
  COP: { code: 'COP', countryCode: 'co', nameFr: 'Peso colombien', countriesFr: ['Colombie'] },
  CRC: { code: 'CRC', countryCode: 'cr', nameFr: 'Colón costaricien', countriesFr: ['Costa Rica'] },
  CUP: { code: 'CUP', countryCode: 'cu', nameFr: 'Peso cubain', countriesFr: ['Cuba'] },
  CVE: { code: 'CVE', countryCode: 'cv', nameFr: 'Escudo cap-verdien', countriesFr: ['Cap-Vert'] },
  CZK: { code: 'CZK', countryCode: 'cz', nameFr: 'Couronne tchèque', countriesFr: ['République Tchèque', 'Prague'] },
  DJF: { code: 'DJF', countryCode: 'dj', nameFr: 'Franc djiboutien', countriesFr: ['Djibouti'] },
  DKK: { code: 'DKK', countryCode: 'dk', nameFr: 'Couronne danoise', countriesFr: ['Danemark', 'Copenhague'] },
  DOP: { code: 'DOP', countryCode: 'do', nameFr: 'Peso dominicain', countriesFr: ['République Dominicaine'] },
  DZD: { code: 'DZD', countryCode: 'dz', nameFr: 'Dinar algérien', countriesFr: ['Algérie', 'Alger'] },
  EGP: { code: 'EGP', countryCode: 'eg', nameFr: 'Livre égyptienne', countriesFr: ['Égypte', 'Le Caire'] },
  ERN: { code: 'ERN', countryCode: 'er', nameFr: 'Nakfa érythréen', countriesFr: ['Érythrée'] },
  ETB: { code: 'ETB', countryCode: 'et', nameFr: 'Birr éthiopien', countriesFr: ['Éthiopie', 'Addis-Abeba'] },
  EUR: { code: 'EUR', countryCode: 'eu', isRegional: true, regionType: 'EUR', nameFr: 'Euro', countriesFr: ['Europe', 'France', 'Allemagne', 'Italie', 'Espagne', 'Belgique', 'Portugal', 'Pays-Bas'] },
  FJD: { code: 'FJD', countryCode: 'fj', nameFr: 'Dollar fidjien', countriesFr: ['Fidji'] },
  FKP: { code: 'FKP', countryCode: 'fk', nameFr: 'Livre des îles Malouines', countriesFr: ['Îles Malouines', 'Falkland'] },
  GBP: { code: 'GBP', countryCode: 'gb', nameFr: 'Livre sterling', countriesFr: ['Royaume-Uni', 'Angleterre', 'Londres', 'Écosse', 'Grande-Bretagne'] },
  GEL: { code: 'GEL', countryCode: 'ge', nameFr: 'Lari géorgien', countriesFr: ['Géorgie'] },
  GHS: { code: 'GHS', countryCode: 'gh', nameFr: 'Cedi ghanéen', countriesFr: ['Ghana', 'Accra'] },
  GIP: { code: 'GIP', countryCode: 'gi', nameFr: 'Livre de Gibraltar', countriesFr: ['Gibraltar'] },
  GMD: { code: 'GMD', countryCode: 'gm', nameFr: 'Dalasi gambien', countriesFr: ['Gambie'] },
  GTQ: { code: 'GTQ', countryCode: 'gt', nameFr: 'Quetzal guatémaltèque', countriesFr: ['Guatemala'] },
  GYD: { code: 'GYD', countryCode: 'gy', nameFr: 'Dollar guyanien', countriesFr: ['Guyana'] },
  HKD: { code: 'HKD', countryCode: 'hk', nameFr: 'Dollar de Hong Kong', countriesFr: ['Hong Kong'] },
  HNL: { code: 'HNL', countryCode: 'hn', nameFr: 'Lempira hondurien', countriesFr: ['Honduras'] },
  HRK: { code: 'HRK', countryCode: 'hr', nameFr: 'Kuna croate', countriesFr: ['Croatie'] },
  HTG: { code: 'HTG', countryCode: 'ht', nameFr: 'Gourde haïtienne', countriesFr: ['Haïti'] },
  HUF: { code: 'HUF', countryCode: 'hu', nameFr: 'Forint hongrois', countriesFr: ['Hongrie', 'Budapest'] },
  IDR: { code: 'IDR', countryCode: 'id', nameFr: 'Roupie indonésienne', countriesFr: ['Indonésie', 'Jakarta', 'Bali'] },
  ILS: { code: 'ILS', countryCode: 'il', nameFr: 'Shekel israélien', countriesFr: ['Israël'] },
  INR: { code: 'INR', countryCode: 'in', nameFr: 'Roupie indienne', countriesFr: ['Inde', 'Delhi', 'Mumbai'] },
  IQD: { code: 'IQD', countryCode: 'iq', nameFr: 'Dinar irakien', countriesFr: ['Irak'] },
  IRR: { code: 'IRR', countryCode: 'ir', nameFr: 'Rial iranien', countriesFr: ['Iran'] },
  ISK: { code: 'ISK', countryCode: 'is', nameFr: 'Couronne islandaise', countriesFr: ['Islande'] },
  JMD: { code: 'JMD', countryCode: 'jm', nameFr: 'Dollar jamaïcain', countriesFr: ['Jamaïque'] },
  JOD: { code: 'JOD', countryCode: 'jo', nameFr: 'Dinar jordanien', countriesFr: ['Jordanie'] },
  JPY: { code: 'JPY', countryCode: 'jp', nameFr: 'Yen japonais', countriesFr: ['Japon', 'Tokyo'] },
  KES: { code: 'KES', countryCode: 'ke', nameFr: 'Shilling kényan', countriesFr: ['Kenya', 'Nairobi'] },
  KGS: { code: 'KGS', countryCode: 'kg', nameFr: 'Som kirghize', countriesFr: ['Kirghizistan'] },
  KHR: { code: 'KHR', countryCode: 'kh', nameFr: 'Riel cambodgien', countriesFr: ['Cambodge'] },
  KMF: { code: 'KMF', countryCode: 'km', nameFr: 'Franc comorien', countriesFr: ['Comores'] },
  KPW: { code: 'KPW', countryCode: 'kp', nameFr: 'Won nord-coréen', countriesFr: ['Corée du Nord'] },
  KRW: { code: 'KRW', countryCode: 'kr', nameFr: 'Won sud-coréen', countriesFr: ['Corée du Sud', 'Séoul'] },
  KWD: { code: 'KWD', countryCode: 'kw', nameFr: 'Dinar koweïtien', countriesFr: ['Koweït'] },
  KYD: { code: 'KYD', countryCode: 'ky', nameFr: 'Dollar des îles Caïmans', countriesFr: ['Îles Caïmans'] },
  KZT: { code: 'KZT', countryCode: 'kz', nameFr: 'Tenge kazakh', countriesFr: ['Kazakhstan'] },
  LAK: { code: 'LAK', countryCode: 'la', nameFr: 'Kip laotien', countriesFr: ['Laos'] },
  LBP: { code: 'LBP', countryCode: 'lb', nameFr: 'Livre libanaise', countriesFr: ['Liban', 'Beyrouth'] },
  LKR: { code: 'LKR', countryCode: 'lk', nameFr: 'Roupie srilankaise', countriesFr: ['Sri Lanka'] },
  LRD: { code: 'LRD', countryCode: 'lr', nameFr: 'Dollar libérien', countriesFr: ['Libéria'] },
  LSL: { code: 'LSL', countryCode: 'ls', nameFr: 'Loti lesothan', countriesFr: ['Lesotho'] },
  LYD: { code: 'LYD', countryCode: 'ly', nameFr: 'Dinar libyen', countriesFr: ['Libye'] },
  MAD: { code: 'MAD', countryCode: 'ma', nameFr: 'Dirham marocain', countriesFr: ['Maroc', 'Casablanca', 'Rabat', 'Marrakech'] },
  MDL: { code: 'MDL', countryCode: 'md', nameFr: 'Leu moldave', countriesFr: ['Moldavie'] },
  MGA: { code: 'MGA', countryCode: 'mg', nameFr: 'Ariary malgache', countriesFr: ['Madagascar'] },
  MKD: { code: 'MKD', countryCode: 'mk', nameFr: 'Denar macédonien', countriesFr: ['Macédoine du Nord'] },
  MMK: { code: 'MMK', countryCode: 'mm', nameFr: 'Kyat birman', countriesFr: ['Birmanie', 'Myanmar'] },
  MNT: { code: 'MNT', countryCode: 'mn', nameFr: 'Tugrik mongol', countriesFr: ['Mongolie'] },
  MOP: { code: 'MOP', countryCode: 'mo', nameFr: 'Pataca macanaise', countriesFr: ['Macao'] },
  MRU: { code: 'MRU', countryCode: 'mr', nameFr: 'Ouguiya mauritanien', countriesFr: ['Mauritanie'] },
  MUR: { code: 'MUR', countryCode: 'mu', nameFr: 'Roupie mauricienne', countriesFr: ['Île Maurice'] },
  MVR: { code: 'MVR', countryCode: 'mv', nameFr: 'Rufiyaa maldivienne', countriesFr: ['Maldives'] },
  MWK: { code: 'MWK', countryCode: 'mw', nameFr: 'Kwacha malawien', countriesFr: ['Malawi'] },
  MXN: { code: 'MXN', countryCode: 'mx', nameFr: 'Peso mexicain', countriesFr: ['Mexique'] },
  MYR: { code: 'MYR', countryCode: 'my', nameFr: 'Ringgit malaisien', countriesFr: ['Malaisie', 'Kuala Lumpur'] },
  MZN: { code: 'MZN', countryCode: 'mz', nameFr: 'Metical mozambicain', countriesFr: ['Mozambique'] },
  NAD: { code: 'NAD', countryCode: 'na', nameFr: 'Dollar namibien', countriesFr: ['Namibie'] },
  NGN: { code: 'NGN', countryCode: 'ng', nameFr: 'Naira nigérian', countriesFr: ['Nigéria', 'Lagos', 'Abuja'] },
  NIO: { code: 'NIO', countryCode: 'ni', nameFr: 'Córdoba nicaraguayen', countriesFr: ['Nicaragua'] },
  NOK: { code: 'NOK', countryCode: 'no', nameFr: 'Couronne norvégienne', countriesFr: ['Norvège', 'Oslo'] },
  NPR: { code: 'NPR', countryCode: 'np', nameFr: 'Roupie népalaise', countriesFr: ['Népal'] },
  NZD: { code: 'NZD', countryCode: 'nz', nameFr: 'Dollar néo-zélandais', countriesFr: ['Nouvelle-Zélande'] },
  OMR: { code: 'OMR', countryCode: 'om', nameFr: 'Rial omanais', countriesFr: ['Oman'] },
  PAB: { code: 'PAB', countryCode: 'pa', nameFr: 'Balboa panaméen', countriesFr: ['Panama'] },
  PEN: { code: 'PEN', countryCode: 'pe', nameFr: 'Sol péruvien', countriesFr: ['Pérou'] },
  PGK: { code: 'PGK', countryCode: 'pg', nameFr: 'Kina papouan', countriesFr: ['Papouasie-Nouvelle-Guinée'] },
  PHP: { code: 'PHP', countryCode: 'ph', nameFr: 'Peso philippin', countriesFr: ['Philippines', 'Manille'] },
  PKR: { code: 'PKR', countryCode: 'pk', nameFr: 'Roupie pakistanaise', countriesFr: ['Pakistan'] },
  PLN: { code: 'PLN', countryCode: 'pl', nameFr: 'Złoty polonais', countriesFr: ['Pologne', 'Varsovie'] },
  PYG: { code: 'PYG', countryCode: 'py', nameFr: 'Guaraní paraguayen', countriesFr: ['Paraguay'] },
  QAR: { code: 'QAR', countryCode: 'qa', nameFr: 'Riyal qatarien', countriesFr: ['Qatar', 'Doha'] },
  RON: { code: 'RON', countryCode: 'ro', nameFr: 'Leu roumain', countriesFr: ['Roumanie', 'Bucarest'] },
  RSD: { code: 'RSD', countryCode: 'rs', nameFr: 'Dinar serbe', countriesFr: ['Serbie', 'Belgrade'] },
  RUB: { code: 'RUB', countryCode: 'ru', nameFr: 'Rouble russe', countriesFr: ['Russie', 'Moscou'] },
  RWF: { code: 'RWF', countryCode: 'rw', nameFr: 'Franc rwandais', countriesFr: ['Rwanda', 'Kigali'] },
  SAR: { code: 'SAR', countryCode: 'sa', nameFr: 'Riyal saoudien', countriesFr: ['Arabie Saoudite', 'Riyad', 'La Mecque'] },
  SBD: { code: 'SBD', countryCode: 'sb', nameFr: 'Dollar des îles Salomon', countriesFr: ['Îles Salomon'] },
  SCR: { code: 'SCR', countryCode: 'sc', nameFr: 'Roupie seychelloise', countriesFr: ['Seychelles'] },
  SDG: { code: 'SDG', countryCode: 'sd', nameFr: 'Livre soudanaise', countriesFr: ['Soudan'] },
  SEK: { code: 'SEK', countryCode: 'se', nameFr: 'Couronne suédoise', countriesFr: ['Suède', 'Stockholm'] },
  SGD: { code: 'SGD', countryCode: 'sg', nameFr: 'Dollar de Singapour', countriesFr: ['Singapour'] },
  SHP: { code: 'SHP', countryCode: 'sh', nameFr: 'Livre de Sainte-Hélène', countriesFr: ['Sainte-Hélène'] },
  SLL: { code: 'SLL', countryCode: 'sl', nameFr: 'Leone sierra-léonais', countriesFr: ['Sierra Leone'] },
  SOS: { code: 'SOS', countryCode: 'so', nameFr: 'Shilling somalien', countriesFr: ['Somalie'] },
  SRD: { code: 'SRD', countryCode: 'sr', nameFr: 'Dollar surinamais', countriesFr: ['Suriname'] },
  STN: { code: 'STN', countryCode: 'st', nameFr: 'Dobra de Sao Tomé', countriesFr: ['Sao Tomé-et-Principe'] },
  SVC: { code: 'SVC', countryCode: 'sv', nameFr: 'Colón salvadorien', countriesFr: ['Salvador'] },
  SYP: { code: 'SYP', countryCode: 'sy', nameFr: 'Livre syrienne', countriesFr: ['Syrie'] },
  SZL: { code: 'SZL', countryCode: 'sz', nameFr: 'Lilangeni swazi', countriesFr: ['Eswatini', 'Swaziland'] },
  THB: { code: 'THB', countryCode: 'th', nameFr: 'Baht thaïlandais', countriesFr: ['Thaïlande', 'Bangkok'] },
  TJS: { code: 'TJS', countryCode: 'tj', nameFr: 'Somoni tadjik', countriesFr: ['Tadjikistan'] },
  TMT: { code: 'TMT', countryCode: 'tm', nameFr: 'Manat turkmène', countriesFr: ['Turkménistan'] },
  TND: { code: 'TND', countryCode: 'tn', nameFr: 'Dinar tunisien', countriesFr: ['Tunisie', 'Tunis'] },
  TOP: { code: 'TOP', countryCode: 'to', nameFr: 'Paʻanga tonguien', countriesFr: ['Tonga'] },
  TRY: { code: 'TRY', countryCode: 'tr', nameFr: 'Livre turque', countriesFr: ['Turquie', 'Istanbul', 'Ankara'] },
  TTD: { code: 'TTD', countryCode: 'tt', nameFr: 'Dollar de Trinité-et-Tobago', countriesFr: ['Trinité-et-Tobago'] },
  TWD: { code: 'TWD', countryCode: 'tw', nameFr: 'Nouveau dollar taïwanais', countriesFr: ['Taïwan'] },
  TZS: { code: 'TZS', countryCode: 'tz', nameFr: 'Shilling tanzanien', countriesFr: ['Tanzanie'] },
  UAH: { code: 'UAH', countryCode: 'ua', nameFr: 'Hryvnia ukrainienne', countriesFr: ['Ukraine', 'Kiev'] },
  UGX: { code: 'UGX', countryCode: 'ug', nameFr: 'Shilling ougandais', countriesFr: ['Ouganda'] },
  USD: { code: 'USD', countryCode: 'us', nameFr: 'Dollar américain', countriesFr: ['États-Unis', 'USA', 'Amérique', 'New York'] },
  UYU: { code: 'UYU', countryCode: 'uy', nameFr: 'Peso uruguayen', countriesFr: ['Uruguay'] },
  UZS: { code: 'UZS', countryCode: 'uz', nameFr: 'Sum ouzbek', countriesFr: ['Ouzbékistan'] },
  VES: { code: 'VES', countryCode: 've', nameFr: 'Bolivar vénézuélien', countriesFr: ['Venezuela'] },
  VND: { code: 'VND', countryCode: 'vn', nameFr: 'Dong vietnamien', countriesFr: ['Vietnam'] },
  VUV: { code: 'VUV', countryCode: 'vu', nameFr: 'Vatu vanuatuan', countriesFr: ['Vanuatu'] },
  WST: { code: 'WST', countryCode: 'ws', nameFr: 'Tala samoan', countriesFr: ['Samoa'] },

  // Regional & Multi-Country Currencies
  XAF: {
    code: 'XAF',
    isRegional: true,
    regionType: 'XAF',
    nameFr: 'Franc CFA (Afrique Centrale - BEAC)',
    countriesFr: [
      'Afrique Centrale', 'CEMAC', 'BEAC',
      'Cameroun', 'Gabon', 'Congo', 'Tchad', 'Centrafrique', 'Guinée Équatoriale',
      'Yaoundé', 'Douala', 'Libreville', 'Brazzaville', 'N\'Djamena'
    ]
  },
  XOF: {
    code: 'XOF',
    isRegional: true,
    regionType: 'XOF',
    nameFr: 'Franc CFA (Afrique de l\'Ouest - BCEAO)',
    countriesFr: [
      'Afrique de l\'Ouest', 'UEMOA', 'BCEAO',
      'Sénégal', 'Côte d\'Ivoire', 'Bénin', 'Burkina Faso', 'Mali', 'Niger', 'Togo', 'Guinée-Bissau',
      'Dakar', 'Abidjan', 'Cotonou', 'Ouagadougou', 'Bamako', 'Niamey', 'Lomé'
    ]
  },
  XCD: {
    code: 'XCD',
    isRegional: true,
    regionType: 'XCD',
    nameFr: 'Dollar des Caraïbes orientales',
    countriesFr: ['Caraïbes Orientales', 'OECS', 'Antigua', 'Dominique', 'Grenade', 'Sainte-Lucie', 'Saint-Vincent']
  },
  XPF: {
    code: 'XPF',
    countryCode: 'pf',
    isRegional: true,
    regionType: 'XPF',
    nameFr: 'Franc CFP (Pacifique)',
    countriesFr: ['Polynésie Française', 'Nouvelle-Calédonie', 'Wallis-et-Futuna', 'Tahiti']
  },
  YER: { code: 'YER', countryCode: 'ye', nameFr: 'Rial yéménite', countriesFr: ['Yémen'] },
  ZAR: { code: 'ZAR', countryCode: 'za', nameFr: 'Rand sud-africain', countriesFr: ['Afrique du Sud', 'Johannesburg', 'Le Cap'] },
  ZMW: { code: 'ZMW', countryCode: 'zm', nameFr: 'Kwacha zambien', countriesFr: ['Zambie'] }
};

export function getCurrencyCountryCode(currencyCode: string): string | undefined {
  return CURRENCY_META_MAP[currencyCode]?.countryCode;
}

export function getCurrencyMeta(currencyCode: string): CurrencyMeta | undefined {
  return CURRENCY_META_MAP[currencyCode];
}
