export const HUMAN_DESC: Record<string, string> = {
  // PDF Tools
  "pdf-to-word": "Convert any PDF into an editable Word document. Text, headings, and tables carry over — download as DOCX ready to edit in Word or Google Docs. Works well on text-based PDFs; scanned files produce simpler output.",
  "pdf-to-text": "Pull the raw text from any PDF in one click. No columns, no formatting — just clean, copyable content ready to paste anywhere. Handles any PDF regardless of how complex the original layout is.",
  "pdf-to-html": "Convert a PDF into clean HTML with real headings and paragraphs. Paste the result directly into any CMS or web editor without cleanup. Best results come from straightforward text documents with clear structure.",
  "pdf-to-epub": "Turn any PDF into a reflowable EPUB for phones, tablets, and e-readers. Compatible with Kindle, Kobo, Apple Books, and any standard reader. Great for reading PDF content comfortably on mobile devices.",
  "pdf-compress": "Shrink PDF file sizes without noticeable quality loss. Useful for email limits and upload size caps — choose your compression level before downloading. Results vary depending on the original content and compression level selected.",
  "pdf-merge": "Combine multiple PDFs into one file. Arrange them in any order before merging, then download the cleanly joined result. Perfect for combining reports, invoices, or any related set of documents.",
  "pdf-split": "Extract specific pages or divide a PDF into smaller files. Choose individual pages or ranges, then download only the sections you need. Save time by working with exactly what matters instead of the whole document.",
  "pdf-rotate": "Fix sideways or upside-down pages from a scan or camera. Rotate one page or all at once, then download the corrected file. Supports 90, 180, and 270 degree rotations.",
  "pdf-unlock": "Remove the password from a protected PDF. Enter the existing password to authorize it, then download a freely shareable, unlocked copy. Does not bypass the password required to open the file.",
  "pdf-protect": "Add a password to any PDF before sending or archiving. Recipients must enter it to open the file — ideal for contracts and sensitive documents. Perfect for adding an extra layer of security to personal or work files.",
  "pdf-page-numbers": "Stamp sequential page numbers onto every page of a PDF. Pick the position and starting number, then download the numbered document. Ideal for manuscripts, reports, and any multi-page document that needs organization.",
  "pdf-watermark": "Add a text watermark across PDF pages. Control the text, opacity, angle, and size — useful for drafts, confidential files, or branded documents. Great for marking documents as confidential or adding your brand before sharing.",
  "pdf-to-image": "Export every PDF page as a PNG or JPEG. Useful for sharing a page visually or embedding it as a graphic anywhere. Choose the format and resolution that work best for your needs.",
  "pdf-to-excel": "Pull tabular data from a PDF into an editable spreadsheet. Rows and columns map to Excel cells — saves hours of manual re-entry. Works well on structured data; scanned PDFs produce messier results.",
  "reorder-pdf": "Drag PDF pages into any order, remove what you don't need, and download a clean reorganized version in seconds. Reorganize entire documents without installing any software. Perfect for fixing the page order of scanned files or rearranging slides.",
  "ocr": "Extract text from scanned documents, photos, and screenshots. Supports multiple languages and handles skewed or low-contrast images well. Runs entirely in your browser — no server involved.",

  // Word & Docs
  "word-to-pdf": "Convert Word documents to PDF with fonts, tables, and spacing fully preserved. Share files that look identical on any device or printer. Fonts, tables, and page breaks all carry over so what you see is what they get.",
  "word-to-text": "Strip all formatting, styles, and tracked changes from a DOCX. Returns clean plain text — ready to paste anywhere without carrying markup across. Handy when you need the raw content without hidden formatting.",
  "word-to-html": "Convert Word documents to clean, semantic HTML without Microsoft bloat. Headings, lists, and links stay intact — paste straight into any CMS. The output is ready to use with minimal cleanup required.",
  "word-to-epub": "Turn a Word document into a reflowable EPUB for reading apps. Works with Kindle, Kobo, Apple Books, and any standard EPUB reader. Documents with clear headings and paragraphs convert cleanest.",
  "word-to-markdown": "Convert Word documents to Markdown. Headings, bold, italic, and lists carry over — ready for GitHub, Notion, or any static site generator. Complex formatting gets simplified but the structure stays intact.",
  "html-to-markdown": "Strip HTML down to clean, portable Markdown. Handles headings, links, and lists — ideal for migrating blog content or CMS output. The result is readable Markdown without tag soup.",
  "markdown-to-pdf": "Render Markdown into a formatted PDF with proper headings, code blocks, and lists. Download a print-ready document in one click. Perfect for turning documentation or README files into a shareable format.",
  "markdown-to-docx": "Convert Markdown to a Word document with proper heading styles. Lists, bold, and italic all convert cleanly for collaborators who use Word. Great for when you write in Markdown but need to send a .docx.",
  "html-to-pdf": "Render any HTML file into a PDF with its styles intact. Useful for archiving pages, generating reports, or capturing designed layouts. Paste your markup, preview the result, and download in seconds.",
  "txt-to-pdf": "Wrap plain text in a clean, well-margined PDF. Share notes, logs, or terminal output as a readable and printable attachment. Content wraps automatically for a clean layout — no special formatting needed.",
  "txt-to-docx": "Convert a plain text file into a Word document in one step — skips the copy-paste into Word, outputs a proper DOCX directly. Saves you the hassle of manually formatting plain text inside Word.",

  // Excel & Spreadsheets
  "excel-to-pdf": "Convert Excel spreadsheets to PDF with tables and formatting intact. Anyone can read the result without needing Excel installed. Each sheet becomes a page in the output with charts preserved.",
  "excel-to-csv": "Export any Excel sheet as a plain CSV that any tool or database can read. Strips formulas and returns clean, portable data rows. Each sheet becomes one CSV file for easy data exchange.",
  "csv-to-excel": "Convert a CSV into a formatted Excel spreadsheet without the import wizard. Useful for sharing data with people who prefer structured files. Column types are auto-detected where the data is clear.",
  "csv-to-json": "Convert CSV to JSON or JSON back to CSV. Move data between formats without writing any code — useful for APIs and apps. Column headers become JSON keys automatically.",
  "csv-viewer": "Open any CSV in a clean, sortable table directly in the browser. No spreadsheet app required to inspect or read the data. Click column headers to sort values in ascending or descending order.",

  // PowerPoint
  "pptx-to-pdf": "Convert a PowerPoint presentation to PDF in one step. Anyone can open the result without PowerPoint — layout and images fully preserved. Each slide becomes a page in the output document.",
  "pptx-to-images": "Export every slide as a PNG image and download them all as a ZIP. Useful for design tools or sharing individual slides as graphics. Each slide is rendered at high resolution for professional use.",
  "pdf-to-pptx": "Convert PDF pages into editable PowerPoint slides. Each page becomes a movable slide element — useful for reusing existing PDF content. Lets you work with PDF material inside PowerPoint without redrawing anything.",

  // Image Tools
  "image-converter": "Convert images between PNG, JPEG, WebP, AVIF, BMP, GIF, TIFF, and ICO. Batch up to 20 files and download all results as a ZIP. All processing happens in your browser — nothing is uploaded.",
  "heic-to-jpg": "Convert iPhone HEIC photos to JPEG for universal compatibility. Supports multiple files at once — opens in any app, viewer, or editor. HEIC is standard on Apple devices but still not widely supported elsewhere.",
  "heic-to-png": "Convert HEIC photos to lossless PNG for broad compatibility. Preserves every pixel exactly and handles multiple files at once. Perfect for when you need full quality without any compatibility issues.",
  "heic-to-webp": "Convert HEIC photos to WebP for smaller files that load fast in modern browsers. Ideal for web publishing and social media. WebP achieves great compression while maintaining visual quality.",
  "heic-to-pdf": "Combine one or more HEIC photos into a single PDF. Each photo gets its own page — useful for sharing iPhone photos as attachments. A simple way to package multiple images into one document.",
  "image-compress": "Reduce image file sizes with an adjustable quality slider. Smaller files upload faster and take less storage — works for JPEG, PNG, and WebP. The before and after sizes update live as you adjust the slider.",
  "image-resize": "Resize any image to exact pixels or a percentage of the original. Lock the aspect ratio to prevent distortion during resizing. Perfect for preparing images for social media, email, or website uploads.",
  "image-crop": "Crop images with interactive drag handles in the browser. Use preset ratios or a custom area, then download at full resolution. Presets include 1:1, 16:9, 4:3, and other common ratios for quick cropping.",
  "image-to-pdf": "Combine one or more images into a single multi-page PDF. Each image gets its own page — useful for bundling photos into one file. Reorder images before generating the final document.",
  "background-remover": "Remove backgrounds from photos using AI. Outputs a transparent PNG ready for designs, presentations, or a new background. Processing happens server-side — your result downloads in seconds.",
  "flip-rotate-image": "Flip or rotate images by any angle. Fix sideways or upside-down photos from cameras and scanners at full resolution. All transformations preserve the original image quality.",
  "watermark-image": "Add a text watermark to photos with control over position, opacity, size, and color. Useful for protecting images from reuse or branding your work. A simple way to mark ownership before sharing online.",
  "favicon-generator": "Generate favicons at every standard size from a single image. Downloads as a ZIP with all files needed for browsers, PWAs, and apps. Includes both PNG files and an .ico file for legacy support.",
  "png-to-webp": "Convert PNG to WebP for smaller files at equivalent visual quality. WebP loads faster and is supported in every modern browser. A quick way to shrink images without visibly changing how they look.",
  "jpg-to-webp": "Convert JPEG to WebP for better compression at similar quality. WebP files are typically 25-35% smaller than JPEG at the same setting. Switch your images to WebP for faster page loads and lower bandwidth.",
  "gif-to-webp": "Convert animated GIFs to WebP for much smaller files that still animate. WebP animations load faster across all modern browsers. Get the same animation at a fraction of the file size.",
  "bmp-to-webp": "Convert BMP to WebP for a dramatic reduction in file size. Efficient compression with no visible quality loss — ideal for web publishing. BMP files are uncompressed and very large; WebP is much more practical.",
  "tiff-to-webp": "Convert TIFF to WebP for web-friendly file sizes. Comparable quality at a fraction of the size — ideal for publishing images online. Great for shrinking scanned documents or photography workflows.",
  "webp-to-png": "Convert WebP back to lossless PNG for apps and platforms that don't support WebP yet. Compatible with all tools and print services. Keeps full quality for use in design apps or archiving.",
  "webp-to-jpg": "Convert WebP to JPEG for maximum compatibility with apps, printers, and older systems. Accepted by virtually every image service. The universal fallback format when WebP isn't supported.",
  "webp-to-pdf": "Combine WebP images into a PDF for sharing or archiving. Each image is placed on its own page in the output document. Useful for including web-optimized images in a clean, printable format.",
  "webp-to-avif": "Convert WebP to AVIF for even better compression at equivalent quality. AVIF typically produces 20-50% smaller files at similar settings. Upgrade your images to the latest format for better compression.",
  "jpg-to-avif": "Convert JPEG to AVIF for noticeably smaller files without visible quality loss. AVIF outperforms JPEG significantly in compression efficiency. Future-proof your images with modern compression technology.",
  "png-to-avif": "Convert PNG to AVIF for modern, efficient compression. Often beats WebP on file size for both lossy and lossless output. Great for reducing storage without deciding between quality modes upfront.",
  "avif-to-jpg": "Convert AVIF to JPEG for compatibility with tools that don't yet support AVIF. JPEG works universally across all apps and services. The safest fallback when you need universal compatibility.",
  "avif-to-png": "Convert AVIF to lossless PNG for full compatibility with software that doesn't support AVIF. Accepted by all design tools. Go back to a fully lossless format when compatibility matters more than size.",
  "jpg-to-png": "Convert JPEG to lossless PNG for transparency support and exact pixel preservation. Useful in tools that require PNG input. PNG supports transparency, which JPEG does not.",
  "png-to-jpg": "Convert PNG to JPEG for smaller file sizes when transparency isn't needed. A quick way to reduce size before uploading or sharing. Best for photos where the file size matters more than perfect precision.",
  "png-to-svg": "Embed a PNG inside an SVG container for platforms that require SVG input. No redrawing needed — the PNG data is included directly. The image stays raster; this is for SVG embedding workflows, not vectorizing.",
  "svg-to-png": "Render SVG graphics to a PNG at the exact pixel dimensions you choose. Useful for exporting icons, logos, and diagrams to raster. Perfect for getting vector graphics into apps that only accept pixel images.",
  "gif-to-png": "Extract the first frame of a GIF as a still PNG. Useful for generating thumbnails or static previews from animated GIF files. Creates a clean preview without keeping the animation data.",
  "bmp-to-jpg": "Convert BMP to JPEG for a dramatic file size reduction. Efficient compression with minimal visible quality loss — easy to share online. BMP files are uncompressed; JPEG handles photos at a fraction of the size.",
  "tiff-to-jpg": "Convert TIFF to JPEG for smaller, shareable files. Keeps visual quality intact while making the file practical to send by email. A simple way to make large scans email-friendly without noticeable quality loss.",
  "tiff-to-png": "Convert TIFF to lossless PNG for broad compatibility. Accepted by virtually all image tools and services without sacrificing quality. Get the same high quality with better cross-platform compatibility.",
  "jpg-to-pdf": "Convert JPEG images into a PDF with each photo on its own page. Combine multiple images into one organized, shareable document. Perfect for sending photos through systems that only accept PDFs.",
  "png-to-pdf": "Convert PNG images into a PDF at full resolution. Each image gets its own page — useful for diagrams, screenshots, and illustrations. Keep your images in order and share them as one clean document.",

  // Privacy
  "metadata-cleaner": "Strip hidden metadata from images and documents before sharing. Removes GPS location, camera model, and author name in seconds. An essential step before publishing files online to protect your privacy.",
  "ai-text-scrubber": "Remove invisible characters and AI detection patterns from any text. Outputs a clean version that reads identically but without embedded signals. Paste your text, clean it, copy the result.",
  "checksum": "Generate and verify SHA-1, SHA-256, and SHA-512 checksums for any file. Compare them to confirm a download hasn't been tampered with. A must-have tool for verifying file integrity after downloading.",

  // Text & Code
  "json-formatter": "Format messy JSON into readable, indented output or minify it to one line. Validates syntax and highlights errors — handles any size JSON. Paste messy JSON and get clean indented output, or the reverse.",
  "html-formatter": "Format or minify HTML markup cleanly and consistently. Useful for reading generated code or preparing markup before deploying to production. Handles any HTML snippet, from inline markup to full documents.",
  "base64": "Encode text or files to Base64, or decode Base64 strings back to their original form. Useful for data URIs, embedded images, and API debugging. Works with both text input and file uploads for maximum flexibility.",
  "url-encoder": "Encode or decode URL components to fix broken query strings. Converts special characters to percent-encoded form — useful for building API requests. Results update in real time as you type.",
  "word-counter": "Count words, characters, sentences, and paragraphs in any text. Also estimates reading time — useful for hitting content length targets. Perfect for writers and students who need to meet word count requirements.",
  "lorem-ipsum": "Generate placeholder text for wireframes and design layouts. Choose paragraphs, sentences, or words — fills any space before real content is ready. Classic Lorem Ipsum included — pick the amount you need and copy it.",

  // Calculators & Utilities
  "password-generator": "Generate strong, random passwords using cryptographic randomness. See the entropy score in bits and customize length, symbols, and character sets. Creates passwords that are truly random and resistant to guessing.",
  "unit-converter": "Convert between units across 13 categories: length, weight, temperature, speed, and more. Type a value and instantly see it in every unit. Pin your most-used conversions for quick access anytime.",
  "currency-converter": "Convert currencies using live rates that update every hour. Falls back to cached rates automatically if the network is unavailable. Track recent conversions and use shortcuts for your most-checked pairs.",
  "qr-code-generator": "Generate QR codes for URLs, text, Wi-Fi credentials, or contact cards. Set the output size and download as PNG at any resolution. Perfect for sharing links or connecting guests to Wi-Fi.",
};
