// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo-concepts/LogoA.tsx": () => import("../components/mockups/logo-concepts/LogoA.tsx"),
  "./components/mockups/logo-concepts/LogoB.tsx": () => import("../components/mockups/logo-concepts/LogoB.tsx"),
  "./components/mockups/logo-concepts/LogoC.tsx": () => import("../components/mockups/logo-concepts/LogoC.tsx")
};
